import {
  andaman,
  barcelona,
  beach1,
  beach2,
  beach3,
  beach4,
  beijingCity,
  ChandranathHill,
  costaBrava,
  dighapatiaRajbari,
  floatingMarkets,
  glassBridge,
  goa,
  granada,
  guliakhaliBeach,
  guthiaMosque,
  jaflong,
  kashmir,
  kerala,
  kuakata,
  ladakh,
  lalakal,
  lauachora,
  madrid,
  mallorca,
  menorca,
  mutianyuWall,
  niladriLake,
  pangthumai,
  patangaBeach,
  puthiaTemple,
  Rajasthan,
  rajshahiUniversity,
  ratargul,
  sanSebastian,
  shanghai,
  shimulBagan,
  sikkim,
  somapuraMahavihara,
  sondip,
  sundarban,
  tajMahal,
  tanguarHaor,
  teaGarden,
  zhangjiajieForest,
} from "~/assets/image/destination";

const destinations = [
  {
    country: "Bangladesh",
    divisions: [
      {
        city: "Cox-Bazar",
        packages: [
          {
            title: "Relaxing Ocean View Stay in Cox's Bazar",
            location: "Cox's Bazar, Bangladesh",
            duration: "3 Days, 2 Nights",
            image: beach3,
          },
          {
            title: "Luxury Beach Resort Experience in Cox's Bazar",
            location: "Cox's Bazar, Bangladesh",
            duration: "4 Days, 3 Nights",
            image: beach1,
          },
          {
            title: "Romantic Beach Getaway for Couples in Cox's Bazar",
            location: "Cox's Bazar, Bangladesh",
            duration: "2 Days, 1 Night",
            image: beach4,
          },
          {
            title: "Family Friendly Beach Vacation in Cox's Bazar",
            location: "Cox's Bazar, Bangladesh",
            duration: "5 Days, 4 Nights",
            image: beach2,
          },
        ],
      },
      {
        city: "Sylhet",
        packages: [
          {
            title: "Scenic Jaflong Hills and River Tour in Sylhet",
            location: "Jaflong, Sylhet",
            duration: "1 Day Tour",
            image: jaflong,
          },
          {
            title: "Blue Waters and Boating at Lalakhal in Sylhet",
            location: "Lalakhal, Sylhet",
            duration: "1 Day Tour",
            image: lalakal,
          },
          {
            title: "Nature Walks in Lauachora Forest, Sylhet",
            location: "Lauachora, Sylhet",
            duration: "2 Days, 1 Night",
            image: lauachora,
          },
          {
            title: "Niladri Lake Visit with Scenic Surroundings",
            location: "Niladri Lake, Sylhet",
            duration: "1 Day Tour",
            image: niladriLake,
          },
          {
            title: "Pangthumai Waterfall Adventure",
            location: "Pangthumai, Sylhet",
            duration: "1 Day Tour",
            image: pangthumai,
          },
          {
            title: "Boat Safari through Ratargul Swamp Forest",
            location: "Ratargul, Sylhet",
            duration: "1 Day Tour",
            image: ratargul,
          },
          {
            title: "Shimul Bagan Forest Excursion in Sylhet",
            location: "Shimul Bagan, Sylhet",
            duration: "1 Day Tour",
            image: shimulBagan,
          },
          {
            title: "Tanguar Haor Floating Village Experience",
            location: "Tanguar Haor, Sylhet",
            duration: "2 Days, 1 Night",
            image: tanguarHaor,
          },
          {
            title: "Walk Through Sylhet’s Tea Garden Landscapes",
            location: "Tea Garden, Sylhet",
            duration: "1 Day Tour",
            image: teaGarden,
          },
        ],
      },
      {
        city: "Chattogram",
        packages: [
          {
            title: "Hiking Chandranath Hill in Chattogram",
            location: "Sitakunda, Chattogram",
            duration: "1 Day Tour",
            image: ChandranathHill,
          },
          {
            title: "Explore Guliakhali Beach and Sand Dunes",
            location: "Guliakhali, Chattogram",
            duration: "1 Day Tour",
            image: guliakhaliBeach,
          },
          {
            title: "Sunset at Patenga Beach with Local Food",
            location: "Patenga, Chattogram",
            duration: "1 Day Tour",
            image: patangaBeach,
          },
          {
            title: "Island Adventure at Sandwip, Chattogram",
            location: "Sandwip, Chattogram",
            duration: "2 Days, 1 Night",
            image: sondip,
          },
        ],
      },
      {
        city: "Rajshahi",
        packages: [
          {
            title: "Visit Historic Dighapatia Rajbari Palace",
            location: "Natore, Rajshahi",
            duration: "1 Day Tour",
            image: dighapatiaRajbari,
          },
          {
            title: "Explore Ancient Puthia Temple Complex",
            location: "Puthia, Rajshahi",
            duration: "1 Day Tour",
            image: puthiaTemple,
          },
          {
            title: "Tour Rajshahi University Campus and Grounds",
            location: "Rajshahi University, Rajshahi",
            duration: "1 Day Tour",
            image: rajshahiUniversity,
          },
          {
            title: "Discover Somapura Mahavihara Ruins",
            location: "Paharpur, Rajshahi",
            duration: "2 Days, 1 Night",
            image: somapuraMahavihara,
          },
        ],
      },
      {
        city: "Barisal",
        packages: [
          {
            title: "Experience Floating Markets of Barisal City",
            location: "Barisal City, Barisal",
            duration: "1 Day Tour",
            image: floatingMarkets,
          },
          {
            title: "Visit Guthia Mosque with Stunning Architecture",
            location: "Barisal Sadar, Barisal",
            duration: "1 Day Tour",
            image: guthiaMosque,
          },
          {
            title: "Relax at Kuakata Beach with Beautiful Views",
            location: "Kuakata, Barisal",
            duration: "3 Days, 2 Nights",
            image: kuakata,
          },
          {
            title: "Explore Sundarban Wildlife and Mangroves",
            location: "Sundarbans, Barisal",
            duration: "4 Days, 3 Nights",
            image: sundarban,
          },
        ],
      },
    ],
  },
  {
    country: "India",
    packages: [
      {
        title: "Rajasthan Royal Heritage Tour with Palaces Visit",
        location: "Rajasthan, India",
        duration: "4 Days, 3 Nights",
        image: Rajasthan,
      },
      {
        title: "Andaman Islands Tropical Island Getaway",
        location: "Andaman, India",
        duration: "5 Days, 4 Nights",
        image: andaman,
      },
      {
        title: "Goa Beach Life with Nightlife and Water Sports",
        location: "Goa, India",
        duration: "3 Days, 2 Nights",
        image: goa,
      },
      {
        title: "Snowy Mountains and Culture of Kashmir",
        location: "Kashmir, India",
        duration: "5 Days, 4 Nights",
        image: kashmir,
      },
      {
        title: "Kerala Backwaters Houseboat and Nature Tour",
        location: "Kerala, India",
        duration: "4 Days, 3 Nights",
        image: kerala,
      },
      {
        title: "Ladakh Mountain Adventure and Monasteries",
        location: "Ladakh, India",
        duration: "6 Days, 5 Nights",
        image: ladakh,
      },
      {
        title: "Sikkim Himalayan Nature and Village Life",
        location: "Sikkim, India",
        duration: "4 Days, 3 Nights",
        image: sikkim,
      },
      {
        title: "Taj Mahal Visit: Monument of Love Tour",
        location: "Agra, India",
        duration: "1 Day Tour",
        image: tajMahal,
      },
    ],
  },
  {
    country: "China",
    packages: [
      {
        title: "Beijing City Tour of History and Culture",
        location: "Beijing, China",
        duration: "3 Days, 2 Nights",
        image: beijingCity,
      },
      {
        title: "Zhangjiajie Glass Bridge Adventure Walk",
        location: "Zhangjiajie, China",
        duration: "2 Days, 1 Night",
        image: glassBridge,
      },
      {
        title: "Hiking Mutianyu Section of Great Wall",
        location: "Mutianyu, China",
        duration: "1 Day Tour",
        image: mutianyuWall,
      },
      {
        title: "Shanghai Modern City and Nightlife Tour",
        location: "Shanghai, China",
        duration: "3 Days, 2 Nights",
        image: shanghai,
      },
      {
        title: "Zhangjiajie Forest with Avatar Mountains",
        location: "Zhangjiajie, China",
        duration: "3 Days, 2 Nights",
        image: zhangjiajieForest,
      },
    ],
  },
  {
    country: "Spain",
    packages: [
      {
        title: "Barcelona Wonders & Culture",
        location: "Barcelona, Spain",
        duration: "3 Days, 2 Nights",
        image: barcelona,
      },
      {
        title: "Costa Brava Beach and Mediterranean Flavors",
        location: "Costa Brava, Spain",
        duration: "2 Days, 1 Night",
        image: costaBrava,
      },
      {
        title: "Granada Alhambra Palace and Historic Tour",
        location: "Granada, Spain",
        duration: "2 Days, 1 Night",
        image: granada,
      },
      {
        title: "Madrid Museums and Historic Squares Visit",
        location: "Madrid, Spain",
        duration: "3 Days, 2 Nights",
        image: madrid,
      },
      {
        title: "Mallorca Island Beaches and Nightlife Tour",
        location: "Mallorca, Spain",
        duration: "4 Days, 3 Nights",
        image: mallorca,
      },
      {
        title: "Menorca Quiet Beaches and Local Life",
        location: "Menorca, Spain",
        duration: "3 Days, 2 Nights",
        image: menorca,
      },
      {
        title: "San Sebastián Culinary and Coastal Tour",
        location: "San Sebastián, Spain",
        duration: "2 Days, 1 Night",
        image: sanSebastian,
      },
    ],
  },
];

export default destinations;
